apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SPRING_APPLICATION_NAME: "user-service"
  SERVER_PORT: "9001"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak:8080/"
  KEYCLOAK_REALM: "kwetter"
  KEYCLOAK_RESOURCE: "admin-cli"
  JWT_ISSUER_URI: "http://172.205.16.15/realms/kwetter"
  JWT_JWK_SET_URI: "http://172.205.16.15/realms/kwetter/protocol/openid-connect/certs"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"